- name: Read messages from a kafka topic and act on them
  hosts: all
  ## Define our source for events
  sources:   
    - ansible.eda.kafka:
        host: 192.168.122.55
        port: 9092
        topic: connect-test

  rules:
    - name: show event body playload
      condition: 
        all:
          - event.body.payload contains "type=SYSCALL"
          - event.body.payload contains "chmod"
      action:
        run_job_template:
          name: "detect-bpfdoor"
          organization: "Default"
          job_args:
            extra_vars:
                event: "{{ event }}"
