- name: Read messages from a kafka topic and act on them
  hosts: all
  ## Define our source for events
  sources:   
    - ansible.eda.kafka:
        host: 192.168.122.55
        port: 9092
        topic: connect-test

  rules:
    #- name: trigger playbook
    #  condition: 
    #    all:
    #      - event.payload contains "type=SYSCALL"
    #      - event.payload contains "chmod"
    #  action:
    #    run_job_template:
    #      name: "detect-bpfdoor"
    #      organization: "Default"
    #      job_args:
    #        extra_vars:
    #            event: "{{ event }}"

    #- name: show event body playload
    #  condition: 
    #    all: 
    #      - event.payload is search("type=SYSCALL", ignorecase=true)
    #      - event.payload is search("chmod", ignorecase=true)
    #  action:
    #    debug:
    #      msg: "Received: {{ event }}"

    - name: string search example
      condition: event.body.payload is search("chmod", ignorecase=true)
      action:
        run_job_template:
          name: "detect-bpfdoor"
          organization: "Default"
          job_args:
            extra_vars:
                event: "{{ event }}"

      #  #all:
      #  #  - event.body.payload is search("chmod", ignorecase=true)
      #  #  - event.body.payload is search("SYSCALL", ignorecase=false)
      #action:
      #  debug:
      #    msg: "Received: {{ event }}"

      #      #print_event:
