---
- name: say thanks
  hosts: "{{ host }}"
  connection: local
  gather_facts: false
  tasks:
    - debug:
        msg: "host:  {{ host }} --- FileSystem: {{ fs }}"
    - debug:
        msg: "Thank you, {{ event.sender | default('my friend') }}!"
