---
- name: Listen for events on a webhook
  hosts: localhost
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: Print complete event content
      condition: event.payload is defined
      action:
        debug:
          msg: "Received event: {{ event | to_nice_json }}"
          
    - name: Disk Utiliation
      condition: event.payload.issue == "disk utilization"
      actions:
        - run_job_template:
            name: "EDA-Notify-Disk-Utilization"
            organization: "Default"
            job_args:
              extra_vars:
                host: "{{ event.payload.host }}"
                fs: "{{ event.payload.fs }}"

    - name: Say Hello
      condition: event.payload.issue == "disk utilization debug"
      #condition: event.payload.message == "Ansible is super cool"
      action:
        debug:
          msg: "You said, '{{ event }}'. Is it me you're looking for?"
          #msg: "You said, '{{ event.payload.message }}'. Is it me you're looking for?"
    #action:
    #  run_playbook:
    #    name: say-what.yml
